#!/bin/bash

SCRIPT_DIR=`dirname "$0"`

DATA_DIR=~/data
BUILD_DIR="$SCRIPT_DIR/build"
EXE="$BUILD_DIR/src/iseql"


if [ "$1" == "make" ]
then
	(
	mkdir -p "$BUILD_DIR"
	cd "$BUILD_DIR"
	cmake -DCMAKE_BUILD_TYPE=Release ..
	make iseql
	)
	exit
fi


if [ ! "$1" ]
then
	echo "You have to specify experiment name"
	exit 1
fi

RESULTS_DIR="$SCRIPT_DIR/results/$1"
mkdir -p "$RESULTS_DIR"



DISABLED_EXPERIMENTS=''

resetDisabledExperiments()
{
	DISABLED_EXPERIMENTS='-'
}


disableLongExperiments()
{
	local DATA=`cat "$1" | grep -B 2 -- '-----END RESULTS-----' | head -n 2`
	local experiments=(`echo "$DATA" | head -n 1`)
	local values=(`echo "$DATA" | tail -n 1`)

	resetDisabledExperiments

	for i in `seq 0 $((${#experiments[*]} - 1))`
	do
		local experiment=${experiments[$i]}
		local time=${values[$i]}
		if [[ "$time" == 'nan' ]] || (( $(bc <<< "$time > 700") ))
		then
			if [ "$DISABLED_EXPERIMENTS" == '-' ]
			then
				DISABLED_EXPERIMENTS="$experiment"
			else
				DISABLED_EXPERIMENTS="$DISABLED_EXPERIMENTS,$experiment"
			fi
		fi
	done
}



experiment()
{
	NAME="$1"
	RESULT_FILE="$RESULTS_DIR/$NAME.txt"
	if [ ! -f "$RESULT_FILE" ]
	then

		#echo "Skipping because $RESULT_FILE exists"
#	else
		echo '---------------------------------------------------------------------------------------'
		echo experiment "${@}"
		echo '---------------------------------------------------------------------------------------'

		"$EXE" "${@:2}" | tee "$RESULTS_DIR/current.txt"
		mv "$RESULTS_DIR/current.txt" "$RESULT_FILE"
	fi

	disableLongExperiments "$RESULT_FILE"
}








resetDisabledExperiments
for c in 1e3 1e4 1e5 1e6 1e7 1e8
do
	for l in 1e1 1e2 1e3 1e4 1e5 1e6
	do
		if [[ "$c" == "1e7" && ("$l" == "1e5" || "$l" == "1e6") ]]
		then
			continue
		fi
		if [[ "$c" == "1e8" && ("$l" == "1e3" || "$l" == "1e4" || "$l" == "1e5" || "$l" == "1e6") ]]
		then
			continue
		fi
		experiment  "reverse-during-$c-$l" reverse-during --exp $c $l --exp $c $l
	done
done


experiment rw-flight reverse-during --file "$DATA_DIR/FLIGHTS_DATA_TABLE.txt"                    --file "$DATA_DIR/FLIGHTS_DATA_TABLE.txt"
experiment rw-inc    reverse-during --file "$DATA_DIR/incumbent-norm.txt"                        --file "$DATA_DIR/incumbent-norm.txt"
experiment rw-web    reverse-during --file "$DATA_DIR/webkit-norm.txt"                           --file "$DATA_DIR/webkit-norm.txt"
experiment rw-basf   reverse-during --basf "$DATA_DIR/basf_nono.import"                          --basf "$DATA_DIR/basf_nono.import"
experiment rw-big    reverse-during --file "$DATA_DIR/big_table-norm.txt"                        --file "$DATA_DIR/big_table-norm.txt"
experiment rw-dasa   reverse-during --dasa "$DATA_DIR/looks_like_one_sensor_data_from_dasa.txt"  --dasa "$DATA_DIR/looks_like_one_sensor_data_from_dasa.txt"

