#!/bin/bash

SCRIPT_DIR=`dirname "$0"`

DATA_DIR=~/data
BUILD_DIR="$SCRIPT_DIR/build"
EXE="$BUILD_DIR/src/iseql"


if [ "$1" == "make" ]
then
	(
	mkdir -p "$BUILD_DIR"
	cd "$BUILD_DIR"
	cmake -DCMAKE_BUILD_TYPE=Release ..
	make iseql
	)
	exit
fi


if [ ! "$1" ]
then
	echo "You have to specify experiment name"
	exit 1
fi

RESULTS_DIR="$SCRIPT_DIR/results/$1"
mkdir -p "$RESULTS_DIR"



DISABLED_EXPERIMENTS=''

resetDisabledExperiments()
{
	DISABLED_EXPERIMENTS='-'
}


disableLongExperiments()
{
	local DATA=`cat "$1" | grep -B 2 -- '-----END RESULTS-----' | head -n 2`
	local experiments=(`echo "$DATA" | head -n 1`)
	local values=(`echo "$DATA" | tail -n 1`)

	resetDisabledExperiments

	for i in `seq 0 $((${#experiments[*]} - 1))`
	do
		local experiment=${experiments[$i]}
		local time=${values[$i]}
		if [[ "$time" == 'nan' ]] || (( $(bc <<< "$time > 700") ))
		then
			if [ "$DISABLED_EXPERIMENTS" == '-' ]
			then
				DISABLED_EXPERIMENTS="$experiment"
			else
				DISABLED_EXPERIMENTS="$DISABLED_EXPERIMENTS,$experiment"
			fi
		fi
	done
}



experiment()
{
	NAME="$1"
	RESULT_FILE="$RESULTS_DIR/$NAME.txt"
	if [ ! -f "$RESULT_FILE" ]
	then

		#echo "Skipping because $RESULT_FILE exists"
#	else
		echo '---------------------------------------------------------------------------------------'
		echo experiment "${@}"
		echo '---------------------------------------------------------------------------------------'

		"$EXE" "${@:2}" | tee "$RESULTS_DIR/current.txt"
		mv "$RESULTS_DIR/current.txt" "$RESULT_FILE"
	fi

	disableLongExperiments "$RESULT_FILE"
}





experiment normal  normal
experiment inlined inlined






scalability()
{
	resetDisabledExperiments
	experiment    scal-$1-$2-e1-1.00    FI   $1 1.00e1 $2    $1 1.00e1 $2    "$DISABLED_EXPERIMENTS"
	experiment    scal-$1-$2-e1-1.78    FI   $1 1.78e1 $2    $1 1.78e1 $2    "$DISABLED_EXPERIMENTS"
	experiment    scal-$1-$2-e1-3.16    FI   $1 3.16e1 $2    $1 3.16e1 $2    "$DISABLED_EXPERIMENTS"
	experiment    scal-$1-$2-e1-5.62    FI   $1 5.62e1 $2    $1 5.62e1 $2    "$DISABLED_EXPERIMENTS"
	experiment    scal-$1-$2-e2-1.00    FI   $1 1.00e2 $2    $1 1.00e2 $2    "$DISABLED_EXPERIMENTS"
	experiment    scal-$1-$2-e2-1.78    FI   $1 1.78e2 $2    $1 1.78e2 $2    "$DISABLED_EXPERIMENTS"
	experiment    scal-$1-$2-e2-3.16    FI   $1 3.16e2 $2    $1 3.16e2 $2    "$DISABLED_EXPERIMENTS"
	experiment    scal-$1-$2-e2-5.62    FI   $1 5.62e2 $2    $1 5.62e2 $2    "$DISABLED_EXPERIMENTS"
	experiment    scal-$1-$2-e3-1.00    FI   $1 1.00e3 $2    $1 1.00e3 $2    "$DISABLED_EXPERIMENTS"
	experiment    scal-$1-$2-e3-1.78    FI   $1 1.78e3 $2    $1 1.78e3 $2    "$DISABLED_EXPERIMENTS"
	experiment    scal-$1-$2-e3-3.16    FI   $1 3.16e3 $2    $1 3.16e3 $2    "$DISABLED_EXPERIMENTS"
	experiment    scal-$1-$2-e3-5.62    FI   $1 5.62e3 $2    $1 5.62e3 $2    "$DISABLED_EXPERIMENTS"
	experiment    scal-$1-$2-e4-1.00    FI   $1 1.00e4 $2    $1 1.00e4 $2    "$DISABLED_EXPERIMENTS"
	experiment    scal-$1-$2-e4-1.78    FI   $1 1.78e4 $2    $1 1.78e4 $2    "$DISABLED_EXPERIMENTS"
	experiment    scal-$1-$2-e4-3.16    FI   $1 3.16e4 $2    $1 3.16e4 $2    "$DISABLED_EXPERIMENTS"
	experiment    scal-$1-$2-e4-5.62    FI   $1 5.62e4 $2    $1 5.62e4 $2    "$DISABLED_EXPERIMENTS"
	experiment    scal-$1-$2-e5-1.00    FI   $1 1.00e5 $2    $1 1.00e5 $2    "$DISABLED_EXPERIMENTS"
	experiment    scal-$1-$2-e5-1.78    FI   $1 1.78e5 $2    $1 1.78e5 $2    "$DISABLED_EXPERIMENTS"
	experiment    scal-$1-$2-e5-3.16    FI   $1 3.16e5 $2    $1 3.16e5 $2    "$DISABLED_EXPERIMENTS"
	experiment    scal-$1-$2-e5-5.62    FI   $1 5.62e5 $2    $1 5.62e5 $2    "$DISABLED_EXPERIMENTS"
	experiment    scal-$1-$2-e6-1.00    FI   $1 1.00e6 $2    $1 1.00e6 $2    "$DISABLED_EXPERIMENTS"
	experiment    scal-$1-$2-e6-1.78    FI   $1 1.78e6 $2    $1 1.78e6 $2    "$DISABLED_EXPERIMENTS"
	experiment    scal-$1-$2-e6-3.16    FI   $1 3.16e6 $2    $1 3.16e6 $2    "$DISABLED_EXPERIMENTS"
	experiment    scal-$1-$2-e6-5.62    FI   $1 5.62e6 $2    $1 5.62e6 $2    "$DISABLED_EXPERIMENTS"
	experiment    scal-$1-$2-e7-1.00    FI   $1 1.00e7 $2    $1 1.00e7 $2    "$DISABLED_EXPERIMENTS"
	experiment    scal-$1-$2-e7-1.78    FI   $1 1.78e7 $2    $1 1.78e7 $2    "$DISABLED_EXPERIMENTS"
	experiment    scal-$1-$2-e7-3.16    FI   $1 3.16e7 $2    $1 3.16e7 $2    "$DISABLED_EXPERIMENTS"
	experiment    scal-$1-$2-e7-5.62    FI   $1 5.62e7 $2    $1 5.62e7 $2    "$DISABLED_EXPERIMENTS"
	experiment    scal-$1-$2-e8-1.00    FI   $1 1.00e8 $2    $1 1.00e8 $2    "$DISABLED_EXPERIMENTS"

	resetDisabledExperiments
	experiment    scal-$1-$2-e8-e1      FI   $1 1.00e8 $2    $1 1.00e1 $2    "$DISABLED_EXPERIMENTS"
	experiment    scal-$1-$2-e8-e2      FI   $1 1.00e8 $2    $1 1.00e2 $2    "$DISABLED_EXPERIMENTS"
	experiment    scal-$1-$2-e8-e3      FI   $1 1.00e8 $2    $1 1.00e3 $2    "$DISABLED_EXPERIMENTS"
	experiment    scal-$1-$2-e8-e4      FI   $1 1.00e8 $2    $1 1.00e4 $2    "$DISABLED_EXPERIMENTS"
	experiment    scal-$1-$2-e8-e5      FI   $1 1.00e8 $2    $1 1.00e5 $2    "$DISABLED_EXPERIMENTS"
	experiment    scal-$1-$2-e8-e6      FI   $1 1.00e8 $2    $1 1.00e6 $2    "$DISABLED_EXPERIMENTS"
	experiment    scal-$1-$2-e8-e7      FI   $1 1.00e8 $2    $1 1.00e7 $2    "$DISABLED_EXPERIMENTS"
}

scalability_for_uni_and_exp()
{
	scalability --uni $1
}

#scalability_for_uni_and_exp 1e3
#scalability_for_uni_and_exp 1e6
#scalability_for_uni_and_exp 1e9



ci_scalability()
{
	resetDisabledExperiments
	experiment    scal-ci-$1-$2-e1-1.00    CI  $1 1.00e1 $2     "$DISABLED_EXPERIMENTS"
	experiment    scal-ci-$1-$2-e1-1.78    CI  $1 1.78e1 $2     "$DISABLED_EXPERIMENTS"
	experiment    scal-ci-$1-$2-e1-3.16    CI  $1 3.16e1 $2     "$DISABLED_EXPERIMENTS"
	experiment    scal-ci-$1-$2-e1-5.62    CI  $1 5.62e1 $2     "$DISABLED_EXPERIMENTS"
	experiment    scal-ci-$1-$2-e2-1.00    CI  $1 1.00e2 $2     "$DISABLED_EXPERIMENTS"
	experiment    scal-ci-$1-$2-e2-1.78    CI  $1 1.78e2 $2     "$DISABLED_EXPERIMENTS"
	experiment    scal-ci-$1-$2-e2-3.16    CI  $1 3.16e2 $2     "$DISABLED_EXPERIMENTS"
	experiment    scal-ci-$1-$2-e2-5.62    CI  $1 5.62e2 $2     "$DISABLED_EXPERIMENTS"
	experiment    scal-ci-$1-$2-e3-1.00    CI  $1 1.00e3 $2     "$DISABLED_EXPERIMENTS"
	experiment    scal-ci-$1-$2-e3-1.78    CI  $1 1.78e3 $2     "$DISABLED_EXPERIMENTS"
	experiment    scal-ci-$1-$2-e3-3.16    CI  $1 3.16e3 $2     "$DISABLED_EXPERIMENTS"
	experiment    scal-ci-$1-$2-e3-5.62    CI  $1 5.62e3 $2     "$DISABLED_EXPERIMENTS"
	experiment    scal-ci-$1-$2-e4-1.00    CI  $1 1.00e4 $2     "$DISABLED_EXPERIMENTS"
	experiment    scal-ci-$1-$2-e4-1.78    CI  $1 1.78e4 $2     "$DISABLED_EXPERIMENTS"
	experiment    scal-ci-$1-$2-e4-3.16    CI  $1 3.16e4 $2     "$DISABLED_EXPERIMENTS"
	experiment    scal-ci-$1-$2-e4-5.62    CI  $1 5.62e4 $2     "$DISABLED_EXPERIMENTS"
	experiment    scal-ci-$1-$2-e5-1.00    CI  $1 1.00e5 $2     "$DISABLED_EXPERIMENTS"
	experiment    scal-ci-$1-$2-e5-1.78    CI  $1 1.78e5 $2     "$DISABLED_EXPERIMENTS"
	experiment    scal-ci-$1-$2-e5-3.16    CI  $1 3.16e5 $2     "$DISABLED_EXPERIMENTS"
	experiment    scal-ci-$1-$2-e5-5.62    CI  $1 5.62e5 $2     "$DISABLED_EXPERIMENTS"
	experiment    scal-ci-$1-$2-e6-1.00    CI  $1 1.00e6 $2     "$DISABLED_EXPERIMENTS"
	experiment    scal-ci-$1-$2-e6-1.78    CI  $1 1.78e6 $2     "$DISABLED_EXPERIMENTS"
	experiment    scal-ci-$1-$2-e6-3.16    CI  $1 3.16e6 $2     "$DISABLED_EXPERIMENTS"
	experiment    scal-ci-$1-$2-e6-5.62    CI  $1 5.62e6 $2     "$DISABLED_EXPERIMENTS"
	experiment    scal-ci-$1-$2-e7-1.00    CI  $1 1.00e7 $2     "$DISABLED_EXPERIMENTS"
	experiment    scal-ci-$1-$2-e7-1.78    CI  $1 1.78e7 $2     "$DISABLED_EXPERIMENTS"
	experiment    scal-ci-$1-$2-e7-3.16    CI  $1 3.16e7 $2     "$DISABLED_EXPERIMENTS"
	experiment    scal-ci-$1-$2-e7-5.62    CI  $1 5.62e7 $2     "$DISABLED_EXPERIMENTS"
	experiment    scal-ci-$1-$2-e8-1.00    CI  $1 1.00e8 $2     "$DISABLED_EXPERIMENTS"
#	experiment    scal-ci-$1-$2-e8-1.78    CI  $1 1.78e8 $2     "$DISABLED_EXPERIMENTS"
#	experiment    scal-ci-$1-$2-e8-3.16    CI  $1 3.16e8 $2     "$DISABLED_EXPERIMENTS"
#	experiment    scal-ci-$1-$2-e8-5.62    CI  $1 5.62e8 $2     "$DISABLED_EXPERIMENTS"
#	experiment    scal-ci-$1-$2-e9-1.00    CI  $1 1.00e9 $2     "$DISABLED_EXPERIMENTS"
}


#ci_scalability --uni 1e1
#ci_scalability --uni 1e2
#ci_scalability --uni 1e3
#ci_scalability --uni 1e5
#ci_scalability --uni 1e6
#ci_scalability --uni 1e8
#ci_scalability --uni 1e9










experiment_rw_fi()
{
	resetDisabledExperiments
	for f in 8 7 6 5 4 3 2 1 0
	do
		experiment  "$1-1e$f"  FI  $2 $3  $2 $3 --subsample "1e$f"  "$DISABLED_EXPERIMENTS"
	done
}




#experiment_rw_fi rw-fi-flight --file "$DATA_DIR/FLIGHTS_DATA_TABLE.txt"
#experiment_rw_fi rw-fi-inc    --file "$DATA_DIR/incumbent-norm.txt"
#experiment_rw_fi rw-fi-web    --file "$DATA_DIR/webkit-norm.txt"
#experiment_rw_fi rw-fi-big    --file "$DATA_DIR/big_table-norm.txt"
#experiment_rw_fi rw-fi-basf   --basf "$DATA_DIR/basf_nono.import"
#experiment_rw_fi rw-fi-dasa   --dasa "$DATA_DIR/looks_like_one_sensor_data_from_dasa.txt"


#experiment rw-ci-flight CI --file "$DATA_DIR/FLIGHTS_DATA_TABLE.txt"                   -
#experiment rw-ci-inc    CI --file "$DATA_DIR/incumbent-norm.txt"                       -
#experiment rw-ci-web    CI --file "$DATA_DIR/webkit-norm.txt"                          -
#experiment rw-ci-big    CI --file "$DATA_DIR/big_table-norm.txt"                       -
#experiment rw-ci-basf   CI --basf "$DATA_DIR/basf_nono.import"                         -
#experiment rw-ci-dasa   CI --dasa "$DATA_DIR/looks_like_one_sensor_data_from_dasa.txt" -


